In [1]:
import numpy as np
import pandas as pd

# Handling Missing Values
Missing values might be the most undesired values in data science.We definitely do not want to have them.
1. Let’s start by creating a sample data frame and adding some missing values to it.

In [2]:
df=pd.DataFrame({
    "Date":pd.date_range(start="2021-10-01",periods=10,freq="D"),
    "Item":1014,
    "Measure_1":np.random.randint(1,10,size=10),
    "Measure_2":np.random.random(10).round(2),
    "Measure_3":np.random.random(10).round(2),
    "Measure_4":np.random.randn(10)
})

In [ ]:
df

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014          9       0.08       0.36   0.632177
1 2021-10-02  1014          5       0.49       0.13   1.392346
2 2021-10-03  1014          8       0.59       0.97  -1.315202
3 2021-10-04  1014          2       0.24       0.52   0.662384
4 2021-10-05  1014          5       0.03       0.51  -1.548388
5 2021-10-06  1014          4       0.55       0.35   1.530959
6 2021-10-07  1014          3       0.81       0.03  -1.258340
7 2021-10-08  1014          2       0.76       0.93   0.201088
8 2021-10-09  1014          6       0.64       0.97  -0.189166
9 2021-10-10  1014          9       0.55       0.66   0.833194

In [3]:
#np.random.randint(1,10,size=10)
# Generate 10 random integers between 1 (inclusive) and 10 (exclusive)
#Generates an array of random floating-point numbers uniformly distributed between 0 (inclusive) and 1 (exclusive).
#10 random numbers from a standard normal distribution with mean 0 and standard deviation 1.
# # Example 2: Hourly frequency
# date_range_hourly = pd.date_range(start="2021-10-01", periods=10, freq="H")
# # Example 4: Monthly frequency (end of the month)
# date_range_monthly = pd.date_range(start="2021-01-01", periods=10, freq="M")
# print("\nMonthly Frequency (Month end):\n", date_range_monthly)

In [ ]:
df

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014          2       0.18       0.83   0.710837
1 2021-10-02  1014          1       0.16       0.38  -1.699820
2 2021-10-03  1014          6       0.85       0.17   2.002979
3 2021-10-04  1014          7       0.83       0.43   0.869157
4 2021-10-05  1014          8       0.81       0.56   0.213789
5 2021-10-06  1014          7       0.28       0.92   0.605320
6 2021-10-07  1014          8       0.79       0.30  -1.850636
7 2021-10-08  1014          1       0.78       0.99   1.161332
8 2021-10-09  1014          4       0.71       0.91  -0.343360
9 2021-10-10  1014          8       0.37       0.69  -0.164941

In [5]:
#find mean and standard deciation of measure_4

In [6]:
#Adding few missing values
df.loc[[2,9],"Item"]=np.nan
df.loc[[2,7,9],"Measure_1"]=np.nan
df.loc[[2,3],"Measure_2"]=np.nan
df.loc[[2],"Measure_3"]=np.nan
df.loc[:6,"Measure_4"]=np.nan

In [7]:
df

        Date    Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014.0        2.0       0.65       0.60        NaN
1 2021-10-02  1014.0        9.0       0.37       0.46        NaN
2 2021-10-03     NaN        NaN        NaN        NaN        NaN
3 2021-10-04  1014.0        6.0        NaN       0.04        NaN
4 2021-10-05  1014.0        8.0       0.78       0.50        NaN
5 2021-10-06  1014.0        9.0       0.45       1.00        NaN
6 2021-10-07  1014.0        8.0       0.19       0.28        NaN
7 2021-10-08  1014.0        NaN       0.70       0.32  -0.447444
8 2021-10-09  1014.0        8.0       0.70       0.66  -2.575019
9 2021-10-10     NaN        NaN       0.40       0.50   1.068550

With Pandas, an integer type missing value representation (<NA>) was introduced so we can have missing values in integer columns as well. However, we need to explicitly declare the data type.

In [8]:
df=df.astype({
    "Item":pd.Int64Dtype(),
    "Measure_1":pd.Int64Dtype()
})

In [9]:
df

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014          2       0.65       0.60        NaN
1 2021-10-02  1014          9       0.37       0.46        NaN
2 2021-10-03  <NA>       <NA>        NaN        NaN        NaN
3 2021-10-04  1014          6        NaN       0.04        NaN
4 2021-10-05  1014          8       0.78       0.50        NaN
5 2021-10-06  1014          9       0.45       1.00        NaN
6 2021-10-07  1014          8       0.19       0.28        NaN
7 2021-10-08  1014       <NA>       0.70       0.32  -0.447444
8 2021-10-09  1014          8       0.70       0.66  -2.575019
9 2021-10-10  <NA>       <NA>       0.40       0.50   1.068550

# Method 1: Drop rows or columns that have a missing value

In [10]:
#One option is to drop the rows or columns that contain a missing value.
df.dropna()
#With the default parameter values, the dropna function drops the rows that contain any
#missing value.

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
8 2021-10-09  1014          8        0.7       0.66  -2.575019

In [11]:
#We can also choose to drop columns that have at least one missing value by using the
#axis parameter.
df.dropna(axis=1)

        Date
0 2021-10-01
1 2021-10-02
2 2021-10-03
3 2021-10-04
4 2021-10-05
5 2021-10-06
6 2021-10-07
7 2021-10-08
8 2021-10-09
9 2021-10-10

In [12]:
#Another situation is to have a column or row that is full of missing values.
#The dropna function can be used for this as well. We just need to change the value of
#how parameter.
df.dropna(how="all")

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014          2       0.65       0.60        NaN
1 2021-10-02  1014          9       0.37       0.46        NaN
2 2021-10-03  <NA>       <NA>        NaN        NaN        NaN
3 2021-10-04  1014          6        NaN       0.04        NaN
4 2021-10-05  1014          8       0.78       0.50        NaN
5 2021-10-06  1014          9       0.45       1.00        NaN
6 2021-10-07  1014          8       0.19       0.28        NaN
7 2021-10-08  1014       <NA>       0.70       0.32  -0.447444
8 2021-10-09  1014          8       0.70       0.66  -2.575019
9 2021-10-10  <NA>       <NA>       0.40       0.50   1.068550

In [13]:
#Drop rows or columns based on a threshold value
#For instance, “thresh=4” means that the rows that have at least 4 non-missing values will be kept. The other ones will be dropped.
df.dropna(thresh=4)

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014          2       0.65       0.60        NaN
1 2021-10-02  1014          9       0.37       0.46        NaN
3 2021-10-04  1014          6        NaN       0.04        NaN
4 2021-10-05  1014          8       0.78       0.50        NaN
5 2021-10-06  1014          9       0.45       1.00        NaN
6 2021-10-07  1014          8       0.19       0.28        NaN
7 2021-10-08  1014       <NA>       0.70       0.32  -0.447444
8 2021-10-09  1014          8       0.70       0.66  -2.575019
9 2021-10-10  <NA>       <NA>       0.40       0.50   1.068550

In [14]:
#Drop based on a particular subset of columns
#The subset parameter of the dropna function is used for this task. For instance,
#we can drop the rows that have a missing value in measure 1 or measure 2 columns as follows:
df.dropna(subset=["Measure_2","Measure_3"])

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014          2       0.65       0.60        NaN
1 2021-10-02  1014          9       0.37       0.46        NaN
4 2021-10-05  1014          8       0.78       0.50        NaN
5 2021-10-06  1014          9       0.45       1.00        NaN
6 2021-10-07  1014          8       0.19       0.28        NaN
7 2021-10-08  1014       <NA>       0.70       0.32  -0.447444
8 2021-10-09  1014          8       0.70       0.66  -2.575019
9 2021-10-10  <NA>       <NA>       0.40       0.50   1.068550

# Method 2: Fill with a constant value

In [15]:
#We can choose a constant value to be used as a replacement for the missing values.
values={"Item":1014,"Measure_1":0}
df.fillna(value=values)

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014          2       0.65       0.60        NaN
1 2021-10-02  1014          9       0.37       0.46        NaN
2 2021-10-03  1014          0        NaN        NaN        NaN
3 2021-10-04  1014          6        NaN       0.04        NaN
4 2021-10-05  1014          8       0.78       0.50        NaN
5 2021-10-06  1014          9       0.45       1.00        NaN
6 2021-10-07  1014          8       0.19       0.28        NaN
7 2021-10-08  1014          0       0.70       0.32  -0.447444
8 2021-10-09  1014          8       0.70       0.66  -2.575019
9 2021-10-10  1014          0       0.40       0.50   1.068550

# Method 3: Fill with an aggregated value

In [16]:
#Another option is to use an aggregated value such as mean, median, or mode.
df["Measure_2"].fillna(df["Measure_2"].mean())

0    0.65
1    0.37
2    0.53
3    0.53
4    0.78
5    0.45
6    0.19
7    0.70
8    0.70
9    0.40
Name: Measure_2, dtype: float64

In [17]:
#df["Measure_1"].fillna(df["Measure_1"].median())
from sklearn.impute import SimpleImputer
my_imputer=SimpleImputer(strategy='median')
my_imputer.fit_transform(np.array(df['Measure_3']).reshape(-1,1))

array([[0.6 ],
       [0.46],
       [0.5 ],
       [0.04],
       [0.5 ],
       [1.  ],
       [0.28],
       [0.32],
       [0.66],
       [0.5 ]])

# Method 4: Replace with the previous or next value

In [18]:
#It is possible to replace the missing values in a column with the previous or next value
# in that column.
#This method might come in handy when working with time-series data.
#Consider you have a data frame that contains the daily temperature measurement
# and the temperate in one day is missing.
#The optimal solution would be to use the temperature in the next or previous day.
df.fillna(method="bfill")

/tmp/ipython-input-815002936.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014          2       0.65       0.60  -0.447444
1 2021-10-02  1014          9       0.37       0.46  -0.447444
2 2021-10-03  1014          6       0.78       0.04  -0.447444
3 2021-10-04  1014          6       0.78       0.04  -0.447444
4 2021-10-05  1014          8       0.78       0.50  -0.447444
5 2021-10-06  1014          9       0.45       1.00  -0.447444
6 2021-10-07  1014          8       0.19       0.28  -0.447444
7 2021-10-08  1014          8       0.70       0.32  -0.447444
8 2021-10-09  1014          8       0.70       0.66  -2.575019
9 2021-10-10  <NA>       <NA>       0.40       0.50   1.068550

In [19]:
#we can limit the number of missing values replaced with this method.
#If we set the limit parameter as 1, then a missing value can only be replaced with its next value.
#The second or third following value will not be used for replacement.
df.fillna(method="bfill",limit=1)

/tmp/ipython-input-2464338646.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill",limit=1)

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014          2       0.65       0.60        NaN
1 2021-10-02  1014          9       0.37       0.46        NaN
2 2021-10-03  1014          6        NaN       0.04        NaN
3 2021-10-04  1014          6       0.78       0.04        NaN
4 2021-10-05  1014          8       0.78       0.50        NaN
5 2021-10-06  1014          9       0.45       1.00        NaN
6 2021-10-07  1014          8       0.19       0.28  -0.447444
7 2021-10-08  1014          8       0.70       0.32  -0.447444
8 2021-10-09  1014          8       0.70       0.66  -2.575019
9 2021-10-10  <NA>       <NA>       0.40       0.50   1.068550

# Method 5: Fill by using another dataframe

We can also pass another data frame to the fillna function. The values in the new data frame will be used to replace the missing values in the current data frame.

The values will be selected according to the row indices and column names. For instance, if there is a missing value in the second row in the item column, the value in the same location in the new data frame will be used.

In [20]:
#Defining a new dataframe
df1=pd.DataFrame({
    "Date":pd.date_range(start="2021-10-01",periods=10,freq="D"),
    "Item":1014,
    "Measure_1":np.random.randint(1,10,size=10),
    "Measure_2":np.random.random(10).round(2),
    "Measure_3":np.random.random(10).round(2),
    "Measure_4":np.random.randn(10)
})
df1

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014          4       0.08       0.63  -1.038696
1 2021-10-02  1014          9       0.31       0.12   0.777571
2 2021-10-03  1014          3       0.86       0.11   0.052303
3 2021-10-04  1014          9       0.99       0.67   0.858289
4 2021-10-05  1014          9       0.18       0.40  -1.239963
5 2021-10-06  1014          2       0.29       0.20   1.528118
6 2021-10-07  1014          4       0.17       0.65   0.142371
7 2021-10-08  1014          3       0.46       0.41  -0.124922
8 2021-10-09  1014          4       0.62       0.48  -0.006555
9 2021-10-10  1014          2       0.05       0.23  -1.073677

In [21]:
#Using df1 to fill missing values in df
df.fillna(df1)

        Date  Item  Measure_1  Measure_2  Measure_3  Measure_4
0 2021-10-01  1014          2       0.65       0.60  -1.038696
1 2021-10-02  1014          9       0.37       0.46   0.777571
2 2021-10-03  1014          3       0.86       0.11   0.052303
3 2021-10-04  1014          6       0.99       0.04   0.858289
4 2021-10-05  1014          8       0.78       0.50  -1.239963
5 2021-10-06  1014          9       0.45       1.00   1.528118
6 2021-10-07  1014          8       0.19       0.28   0.142371
7 2021-10-08  1014          3       0.70       0.32  -0.447444
8 2021-10-09  1014          8       0.70       0.66  -2.575019
9 2021-10-10  1014          2       0.40       0.50   1.068550

# Method 6: Using Random Forest classifier to impute missing values

In [33]:
%pip install --upgrade scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 42.9 MB/s eta 0:00:00
Installing collected packages: scikit-learn
Successfully installed scikit-learn-1.8.0

In [1]:
import sklearn
print(sklearn.__version__)

1.8.0

In [2]:
import numpy as np
import pandas as pd

# MUST be imported first
from sklearn.experimental import enable_iterative_imputer  # noqa

from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

In [3]:
df = pd.DataFrame({
    "Age": [25, 30, np.nan, 45, 50, np.nan],
    "Income": [50000, np.nan, 60000, 80000, np.nan, 70000],
    "Gender": [0, 1, 1, np.nan, 0, 1]  # categorical (0/1)
})

print("Original Data")
print(df)

Original Data
    Age   Income  Gender
0  25.0  50000.0     0.0
1  30.0      NaN     1.0
2   NaN  60000.0     1.0
3  45.0  80000.0     NaN
4  50.0      NaN     0.0
5   NaN  70000.0     1.0

In [4]:
num_imputer = IterativeImputer(
    estimator=RandomForestRegressor(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    ),
    max_iter=10,
    random_state=42
)

df[["Age", "Income"]] = num_imputer.fit_transform(df[["Age", "Income"]])

In [5]:
cat_imputer = IterativeImputer(
    estimator=RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    ),
    max_iter=10,
    random_state=42
)

df[["Gender"]] = np.round(
    cat_imputer.fit_transform(df[["Gender"]])
).astype(int)

In [7]:
print("\nImputed Data")
print(df)

Imputed Data
     Age   Income  Gender
0  25.00  50000.0       0
1  30.00  58600.0       1
2  30.15  60000.0       1
3  45.00  80000.0       1
4  50.00  71500.0       0
5  47.50  70000.0       1